# web
server:
  port: 32001
  tomcat:
    accept-count: 2000

# eureka 注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL:http://eureka_admin:eureka_admin1!3@eureka:38761/eureka/}
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 5

# feign
feign:
  client:
    config:
      default:
        # connect timeout
        connect-timeout: ${FEIGN_CONNECT_TIMEOUT:2000}
        # read timeout
        read-timeout: ${FEIGN_READ_TIMEOUT:5000}

# dubbo 服务提供端
dubbo:
  cloud:
    subscribed-services: null
  protocol:
    name: dubbo
    port: ${DUBBO_PROTOCOL_PORT:-1}
  provider:
    timeout: ${DUBBO_PROVIDER_TIMEOUT:30000}

# resources
spring:

  cloud:
    # nacos 注册中心
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:http://127.0.0.1:8848}
      discovery:
        cluster-name: ${NACOS_DISCOVERY_CLUSTER_NAME:DEFAULT}
        username: ${NACOS_DISCOVERY_USERNAME:nacos}
        password: ${NACOS_DISCOVERY_PASSWORD:nacos}
        namespace: ${NACOS_DISCOVERY_NAMESPACE:public}
        group: ${NACOS_DISCOVERY_NAMESPACE:DEFAULT_GROUP}
        ephemeral: ${NACOS_DISCOVERY_EPHEMERAL:true}
        weight: ${NACOS_DISCOVERY_WEIGHT:1}
    # sentinel
    sentinel:
      transport:
        dashboard: ${SENTINEL_TRANSPORT_DASHBOARD:127.0.0.1:3761}

  #application
  application:
    name: ${APPLICATION_NAME:xxl-job-executor-base}

  #main
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  # redis
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:admin1!3}
    database: ${REDIS_DATABASE:0}
    jedis:
      pool:
        max-active: ${REDIS_POOL_ACTIVE:100}
        max-wait: ${REDIS_POOL_MAX_WAIT:10s}
        max-idle: ${REDIS_POOL_MAX_IDLE:20}
        min-idle: ${REDIS_POOL_MIN_IDLE:10}

# actuator/info
management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always #默认是never

### xxl-job executor
xxl:
  job:
    executor:
      title: 基础执行器
      logpath: /home/logs/job-executor-base-log
      logretentiondays: 7