# web
server:
  port: 32001
  tomcat:
    accept-count: 2000

# 注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL:http://eureka_admin:eureka_admin1!3@127.0.0.1:8761/eureka/}
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 5

# resources
spring:
  #application
  application:
    name: ${APPLICATION_NAME:xxl-job-executor-base}
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  # redis
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:admin1!3}
    database: ${REDIS_DATABASE:0}
    jedis:
      pool:
        max-active: ${REDIS_POOL_ACTIVE:100}
        max-wait: ${REDIS_POOL_MAX_WAIT:10s}
        max-idle: ${REDIS_POOL_MAX_IDLE:20}
        min-idle: ${REDIS_POOL_MIN_IDLE:10}

# actuator/info
management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always #默认是never

### xxl-job executor
xxl:
  job:
    executor:
      title: 基础执行器
      logpath: /home/logs/job-executor-base-log
      logretentiondays: 7