# 30000-32767
server:
  port: 31001
  tomcat:
    accept-count: 2000

# eureka 注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL:http://eureka_admin:eureka_admin1!3@127.0.0.1:8761/eureka/}
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 5

# spring
spring:

  cloud:
    # nacos 注册中心
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:http://127.0.0.1:8848}
      discovery:
        cluster-name: ${NACOS_DISCOVERY_CLUSTER_NAME:DEFAULT}
        username: ${NACOS_DISCOVERY_USERNAME:nacos}
        password: ${NACOS_DISCOVERY_PASSWORD:nacos}
        namespace: ${NACOS_DISCOVERY_NAMESPACE:public}
        group: ${NACOS_DISCOVERY_NAMESPACE:DEFAULT_GROUP}
        ephemeral: ${NACOS_DISCOVERY_EPHEMERAL:true}
        weight: ${NACOS_DISCOVERY_WEIGHT:1}
    # sentinel
    sentinel:
      transport:
        dashboard: ${SENTINEL_TRANSPORT_DASHBOARD:127.0.0.1:3761}


  #application
  application:
    name: ${APPLICATION_NAME:tiny-basics-api-server}

  #main
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  #servlet
  servlet:
    multipart:
      # 上传文件总的最大值
      max-request-size: ${SERVLET_MUTIPART_MAX_REQUEST_SIZE:100MB}
      # 单个文件的最大值
      max-file-size: ${SERVLET_MUTIPART_MAX_FILE_SIZE:50MB}

  # datasource
  datasource:
    defaultDb: enable
    driver: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/xxl_job}
    repositoryName: ${DATASOURCE_REPOSITORY_NAME:postgres}
    repositoryWord: ${DATASOURCE_REPOSITORY_WORD:12345678}
    # datasource-pool
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: ${HIKARI_MINIMUM_IDLE:10}
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:30}
      auto-commit: ${HIKARI_AUTO_COMMIT:true}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:30000}
      pool-name: HikariCP
      max-lifetime: ${HIKARI_MAX_LIFETIME:900000}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:10000}
      connection-test-query: ${HIKARI_CONNECTION_TEST_QUERY:SELECT 1}
      validation-timeout: ${HIKARI_VALIDATION_TIMEOUT:1000}

  # jpa
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${HIBERNATE_SHOW_SQL:true}

  # redis
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:admin1!3}
    database: ${REDIS_DATABASE:0}
    jedis:
      pool:
        max-active: ${REDIS_POOL_ACTIVE:100}
        max-wait: ${REDIS_POOL_MAX_WAIT:10s}
        max-idle: ${REDIS_POOL_MAX_IDLE:20}
        min-idle: ${REDIS_POOL_MIN_IDLE:10}

  # kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9093}

  # jackson
  jackson:
    serialization:
      fail-on-empty-beans: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

# mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml, classpath*:mapper/**/*.xml

# actuator/info
management:
  endpoints:
    web:
      exposure:
        include: info,health

# xls 初始化数据
api-server:
  xls:
    init-data: ${XLS_INITDATA:true}

### xxl-job executor
xxl:
  job:
    executor:
      title: 基础接口服务
      logpath: /home/logs/job-api-server-log
      logretentiondays: 7

# swagger开关
swagger:
  show: ${SWAGGER_SHOW:true}